"""Taxonomies, outcome enums, rule IDs, and versions for Phase 10."""

from enum import IntEnum, StrEnum

POLICY_SCHEMA_VERSION: str = "policy-config-v1"
POLICY_VERSION: str = "policy-v1"
RULE_SET_VERSION: str = "ruleset-v1"
POLICY_DECISION_SCHEMA_VERSION: str = "policy-decision-v1"
POLICY_TRACE_SCHEMA_VERSION: str = "policy-trace-v1"
POLICY_ARTIFACT_SCHEMA_VERSION: str = "policy-artifact-v1"


class PolicyOutcome(StrEnum):
    """Explicit deterministic policy evaluation outcome."""

    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    REQUIRE_HUMAN_APPROVAL = "REQUIRE_HUMAN_APPROVAL"


class PolicyReasonCode(StrEnum):
    """Stable machine-readable reason codes for policy evaluations."""

    PAYMENT_ALREADY_RECOVERED = "PAYMENT_ALREADY_RECOVERED"
    INVALID_EVENT = "INVALID_EVENT"
    DUPLICATE_EVENT = "DUPLICATE_EVENT"
    UNSUPPORTED_ACTION = "UNSUPPORTED_ACTION"
    INVALID_MODEL_OUTPUT = "INVALID_MODEL_OUTPUT"
    MAX_RETRIES_REACHED = "MAX_RETRIES_REACHED"
    RETRY_COOLDOWN_ACTIVE = "RETRY_COOLDOWN_ACTIVE"
    MAX_SAME_ACTION_REPETITIONS_REACHED = "MAX_SAME_ACTION_REPETITIONS_REACHED"
    MAX_TOTAL_INTERVENTIONS_REACHED = "MAX_TOTAL_INTERVENTIONS_REACHED"
    HIGH_VALUE_REQUIRES_APPROVAL = "HIGH_VALUE_REQUIRES_APPROVAL"
    LOW_CONFIDENCE_REQUIRES_APPROVAL = "LOW_CONFIDENCE_REQUIRES_APPROVAL"
    INSUFFICIENT_EXPECTED_VALUE = "INSUFFICIENT_EXPECTED_VALUE"
    NEGATIVE_EXPECTED_VALUE = "NEGATIVE_EXPECTED_VALUE"
    STALE_OR_INCONSISTENT_EVENT = "STALE_OR_INCONSISTENT_EVENT"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
    PAYMENT_LINK_CAPACITY_REACHED = "PAYMENT_LINK_CAPACITY_REACHED"
    DUPLICATE_PAYMENT_LINK = "DUPLICATE_PAYMENT_LINK"
    MODEL_A_FAILURE = "MODEL_A_FAILURE"
    MODEL_B_FAILURE = "MODEL_B_FAILURE"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_MISMATCH = "APPROVAL_MISMATCH"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    POLICY_ALLOWED = "POLICY_ALLOWED"


class RulePrecedenceLevel(IntEnum):
    """Priority levels for policy rule resolution (lower is higher priority)."""

    HARD_SAFETY_BLOCK = 1
    STALE_UNKNOWN_STATE = 2
    UNSUPPORTED_ACTION = 3
    ATTEMPT_INTERVENTION_LIMIT = 4
    INVALID_MODEL_OUTPUT = 5
    CONFIDENCE_ECONOMIC_GUARDRAIL = 6
    HUMAN_APPROVAL_REQUIREMENT = 7
    ALLOW = 8


class RuleId(StrEnum):
    """Unique identifiers for all registered policy and safety rules."""

    H1_PAYMENT_CAPTURED = "H1_PAYMENT_CAPTURED"
    H2_INVALID_EVENT = "H2_INVALID_EVENT"
    H3_DUPLICATE_EVENT = "H3_DUPLICATE_EVENT"
    H4_UNSUPPORTED_ACTION = "H4_UNSUPPORTED_ACTION"
    H5_INVALID_MODEL_OUTPUT = "H5_INVALID_MODEL_OUTPUT"
    R1_RETRY_LIMIT = "R1_RETRY_LIMIT"
    R2_RETRY_COOLDOWN = "R2_RETRY_COOLDOWN"
    R3_SAME_ACTION_LIMIT = "R3_SAME_ACTION_LIMIT"
    R4_TOTAL_INTERVENTION_LIMIT = "R4_TOTAL_INTERVENTION_LIMIT"
    S1_HIGH_VALUE = "S1_HIGH_VALUE"
    S2_LOW_CONFIDENCE = "S2_LOW_CONFIDENCE"
    S3_MIN_ERV = "S3_MIN_ERV"
    S4_NEGATIVE_ERV = "S4_NEGATIVE_ERV"
    S5_STALE_STATE = "S5_STALE_STATE"
    S6_RECONCILIATION = "S6_RECONCILIATION"
    S7_PAYMENT_LINK_CAPACITY = "S7_PAYMENT_LINK_CAPACITY"
    S8_IDEMPOTENCY_CONFLICT = "S8_IDEMPOTENCY_CONFLICT"
    A1_APPROVAL_REQUIRED = "A1_APPROVAL_REQUIRED"
    A2_APPROVAL_MISMATCH = "A2_APPROVAL_MISMATCH"
    A3_APPROVAL_EXPIRED = "A3_APPROVAL_EXPIRED"
    M1_MODEL_A_FAILURE = "M1_MODEL_A_FAILURE"
    M2_MODEL_B_FAILURE = "M2_MODEL_B_FAILURE"


__all__ = [
    "POLICY_ARTIFACT_SCHEMA_VERSION",
    "POLICY_DECISION_SCHEMA_VERSION",
    "POLICY_SCHEMA_VERSION",
    "POLICY_TRACE_SCHEMA_VERSION",
    "POLICY_VERSION",
    "RULE_SET_VERSION",
    "PolicyOutcome",
    "PolicyReasonCode",
    "RuleId",
    "RulePrecedenceLevel",
]
