"""APRO persistence package exports."""

from apro.persistence.base import Base
from apro.persistence.database import get_async_engine, get_session_factory
from apro.persistence.mapper import (
    action_evaluation_to_domain,
    action_evaluation_to_orm,
    audit_event_to_domain,
    audit_event_to_orm,
    customer_to_domain,
    customer_to_orm,
    decision_to_domain,
    decision_to_orm,
    diagnosis_to_domain,
    diagnosis_to_orm,
    execution_to_domain,
    execution_to_orm,
    outcome_to_domain,
    outcome_to_orm,
    payment_event_to_domain,
    payment_event_to_orm,
    payment_to_domain,
    payment_to_orm,
    policy_decision_to_domain,
    policy_decision_to_orm,
    recovery_action_to_domain,
    recovery_action_to_orm,
    recovery_case_to_domain,
    recovery_case_to_orm,
)
from apro.persistence.models import (
    ActionEvaluationModel,
    AuditEventModel,
    CustomerModel,
    DecisionModel,
    DiagnosisModel,
    ExecutionModel,
    OutcomeModel,
    PaymentEventModel,
    PaymentModel,
    PolicyDecisionModel,
    RawEventModel,
    RecoveryActionModel,
    RecoveryCaseModel,
)
from apro.persistence.repositories import (
    ActionEvaluationRepository,
    AuditEventRepository,
    CustomerRepository,
    DecisionRepository,
    DiagnosisRepository,
    ExecutionRepository,
    OutcomeRepository,
    PaymentEventRepository,
    PaymentRepository,
    PolicyDecisionRepository,
    RawEventRepository,
    RecoveryActionRepository,
    RecoveryCaseRepository,
)
from apro.persistence.unit_of_work import UnitOfWork

__all__ = [
    "Base",
    "get_async_engine",
    "get_session_factory",
    "UnitOfWork",
    # ORM Models
    "CustomerModel",
    "PaymentModel",
    "RawEventModel",
    "PaymentEventModel",
    "RecoveryCaseModel",
    "RecoveryActionModel",
    "DiagnosisModel",
    "ActionEvaluationModel",
    "DecisionModel",
    "PolicyDecisionModel",
    "ExecutionModel",
    "OutcomeModel",
    "AuditEventModel",
    # Mappers
    "customer_to_orm",
    "customer_to_domain",
    "payment_to_orm",
    "payment_to_domain",
    "payment_event_to_orm",
    "payment_event_to_domain",
    "recovery_case_to_orm",
    "recovery_case_to_domain",
    "recovery_action_to_orm",
    "recovery_action_to_domain",
    "diagnosis_to_orm",
    "diagnosis_to_domain",
    "action_evaluation_to_orm",
    "action_evaluation_to_domain",
    "decision_to_orm",
    "decision_to_domain",
    "policy_decision_to_orm",
    "policy_decision_to_domain",
    "execution_to_orm",
    "execution_to_domain",
    "outcome_to_orm",
    "outcome_to_domain",
    "audit_event_to_orm",
    "audit_event_to_domain",
    # Repositories
    "CustomerRepository",
    "PaymentRepository",
    "RawEventRepository",
    "PaymentEventRepository",
    "RecoveryCaseRepository",
    "RecoveryActionRepository",
    "DiagnosisRepository",
    "ActionEvaluationRepository",
    "DecisionRepository",
    "PolicyDecisionRepository",
    "ExecutionRepository",
    "OutcomeRepository",
    "AuditEventRepository",
]
