"""Data models, eligibility, and utility schemas for APRO Phase 9 Decision Engine."""

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from apro.decision.enums import (
    DECISION_MODEL_SCHEMA_VERSION,
    ECONOMIC_CONFIG_SCHEMA_VERSION,
    POLICY_CONFIG_SCHEMA_VERSION,
    UTILITY_FORMULA_VERSION,
    DecisionStatus,
)
from apro.recovery_prediction.enums import (
    RECOVERY_ACTION_SCHEMA_VERSION,
    RecoveryAction,
)
from apro.recovery_prediction.features import (
    RECOVERY_OUTCOME_FEATURE_SCHEMA_VERSION,
)


class ActionEligibility(BaseModel):
    """Eligibility status and evaluation rationale for a candidate action."""

    model_config = ConfigDict(frozen=True)

    action: RecoveryAction
    is_eligible: bool
    reason: str | None = None
    policy_rule: str | None = None


class ActionCostConfig(BaseModel):
    """Cost, friction, and penalty parameters for an action in paise."""

    model_config = ConfigDict(frozen=True)

    action_cost: int = Field(default=0, ge=0)
    operational_cost: int = Field(default=0, ge=0)
    customer_friction_cost: int = Field(default=0, ge=0)
    risk_penalty: int = Field(default=0, ge=0)

    @property
    def total_cost(self) -> int:
        return (
            self.action_cost
            + self.operational_cost
            + self.customer_friction_cost
            + self.risk_penalty
        )


class ActionUtility(BaseModel):
    """Full economic utility decomposition for a candidate recovery action."""

    model_config = ConfigDict(frozen=True)

    action: RecoveryAction
    eligible: bool
    reason_if_ineligible: str | None = None
    predicted_success_probability: float = Field(ge=0.0, le=1.0)
    predicted_recovered_amount: int = Field(ge=0)
    expected_gross_recovery: int = Field(ge=0)
    action_cost: int = Field(ge=0)
    operational_cost: int = Field(ge=0)
    customer_friction_cost: int = Field(ge=0)
    risk_penalty: int = Field(ge=0)
    expected_recovery_value: int
    utility_version: str = Field(default=UTILITY_FORMULA_VERSION)

    @property
    def total_cost(self) -> int:
        return (
            self.action_cost
            + self.operational_cost
            + self.customer_friction_cost
            + self.risk_penalty
        )


class RecoveryDecision(BaseModel):
    """Immutable, serializable recovery decision generated by Phase 9 Engine."""

    model_config = ConfigDict(frozen=True)

    decision_id: str
    record_id: str
    scenario_id: str
    recovery_case_id: str | None = None
    selected_action: RecoveryAction | None = None
    decision_status: DecisionStatus
    expected_recovery_value: int | None = None
    expected_gross_recovery: int | None = None
    expected_cost: int | None = None
    utility_by_action: dict[RecoveryAction, ActionUtility]
    eligibility_by_action: dict[RecoveryAction, ActionEligibility]
    decision_confidence: float = Field(ge=0.0, le=1.0)
    rationale: str
    decision_latency_ms: float = Field(default=0.0, ge=0.0)
    diagnosis_model_version: str
    outcome_model_version: str
    policy_version: str = Field(default=POLICY_CONFIG_SCHEMA_VERSION)
    economic_config_version: str = Field(default=ECONOMIC_CONFIG_SCHEMA_VERSION)
    decision_model_version: str = Field(default=DECISION_MODEL_SCHEMA_VERSION)
    action_schema_version: str = Field(default=RECOVERY_ACTION_SCHEMA_VERSION)
    feature_schema_version: str = Field(default=RECOVERY_OUTCOME_FEATURE_SCHEMA_VERSION)
    dataset_version: str
    evaluation_run_id: str | None = None
    provenance: dict[str, Any] = Field(default_factory=dict)
